### ISSUE TITLE
Autocomplete should have an option to remain closed

### ISSUE THREAD

**Issue by Foxandxss** [metadevpro/lux#124]
When the autocomplete has a value and you click the `x` to remove it, it automatically opens again. We should have either an option to "remain closed" or the other way around, an option to have it open again after cleaning the value.

**Comment by pjmolina** [comment]
Implementation proposal and default value:
```
/** After cleaning the selection should the completion list remain open or closed:
   *  true: open for form fields (when the action most likely is to pick another one).
   *  false: (default) close on filters, to clean a filter and select all.
   */
  @Input() keepOpenAfterDelete = false;
```
