### ISSUE TITLE
Geoposition: same style as lux-input

### ISSUE THREAD

**Issue by pjmolina** [metadevpro/lux#144]
Use CSS variables to ensure same styles as lux-input including:
- padding
- margin
- border color and border-radius

@Foxandxss  will review this PR

**Comment by JavierCenteno** [comment]
En Geolocation: Poner padding-right en los input y usar el espacio para meter la letras de los puntos cardinales para que aparezcan dentro de los inputs. Básicamente, para que aparezcan los inputs de geolocation como aparecen los inputs de fecha y hora en el chrome.
Cambiar el icono del mundo en el botón de abrir modal de un emoji a un svg que nos dé paco.
