### ISSUE TITLE
passing down id to component's input

### ISSUE THREAD

**Issue by Foxandxss** [metadevpro/lux#52]
We have several components that instantiates an inner input, for example:

```
<lux-input ...></lux-input>
<lux-select ...></lux-select>
<lux-filter ...></lux-filter>
```

The inner input needs an id but if we add it to the host element, it will be duplicated.

The options are:

```
<lux-input id="foo"></lux-input>
```

And then:

```
this.renderer.removeAttribute(this.element.nativeElement, "id");
```

To remove it after we assign it to the inner input. That works but it is kind of a workaround.

Another option would be to use a different attribute in the host other than `id`. We could do

```
<lux-input name="foo">
```

And that will internally set the `id` to the input to `foo`. That way there is no clash.

**Comment by pjmolina** [comment]
+1 `name` seems a better choice for me. No need to remove attributes this way.

**Comment by Foxandxss** [comment]
We decided for inputId at the end.
